### ISSUE TITLE
Would it be possible to update this?

### ISSUE THREAD

**Issue by polinabee** [factbook/factbook.json#1]
First off thanks for creating this data set, it's been useful to me in a project. Would it be possible to update this with the most recent factbook data? 
Also, is there a reason for selecting countries as opposed to using every entity provided in the factbook?

**Comment by geraldb** [comment]
Welcome. Please post comments, questions and suggestions to the [mailing list/forum](http://groups.google.com/group/openmundi) - so others can join in. The issues here are only used for bug tracking. Cheers.

**Comment by polinabee** [comment]
Thanks, sorry about that - I am new to github. So would I be able to build
the datasets on my own using the build repo?
According to the latest comment, the html has changed. This means that the
build would not work currently, correct?
Thank you!

On Tue, Apr 14, 2015 at 9:38 AM, Gerald Bauer notifications@github.com
wrote:

> Closed #1 https://github.com/openmundi/factbook.json/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openmundi/factbook.json/issues/1#event-281142491.

## 

Polina Berenstein
Product Associate at FindTheBest.com
GIS | Ecology, Behavior, and Evolution B.S. UCLA '14
Email: polinaberen@gmail.com polinaber@gmail.com
Cell: 415-418-9072
