### ISSUE TITLE
Question: API Available?

### ISSUE THREAD

**Issue by tderflinger** [factbook/factbook.json#12]
Hi there!

First of all thanks for this fantastic work! My question is: Do you know any open source REST API for the World Factbook that I could use?

Thanks,
-Thomas

**Comment by geraldb** [comment]
@tderflinger  Not sure I understand.   This is a REST HTTP API for the World Factbook.   What is missing?

For example, for Germany (gm) try <https://github.com/factbook/factbook.json/raw/master/europe/gm.json> and so on.

Note: The data gets updated once a week.   For more questions, please see  (and post to) <https://github.com/factbook/factbook.json#questions-comments>
