### ISSUE TITLE
ZA is incorrectly stored as Zambia

### ISSUE THREAD

**Issue by gee-forr** [factbook/factbook.json#2]
Hey there,

I noticed that you've got Zambian data under ZA for the African region... It should be South African data...

p.s - thanks for this, it's quite useful

**Comment by gee-forr** [comment]
Uhhh... nevermind, I see it's stored under SF. Weird, but, ok :)

Thanks for this valuable resource, nonetheless.

**Comment by geraldb** [comment]
@gee-forr  FYI: The codes are not ISO country codes but GEC (FIPS) country codes - see a [mapping here](https://github.com/factbook/factbook.csv/blob/master/codes.csv).
