### ISSUE TITLE
Non-standard name properties on cc, sk

### ISSUE THREAD

**Issue by mn113** [factbook/factbook.json#4]
A couple of countries in the dataset don't conform to a standard way to programmatically access their names. I think it's just Curacao (cc) and Sint Maarten (sk).

Their names are both stored under `["Government"]["Country name"]["Dutch short form"]`.
Every other country uses `["Government"]["Country name"]["conventional short form"]`.

I gather this is just a harvested dataset rather than a curated one, but how do you feel about this? If people want to use this data programatically, it's inconvenient that something as major as the _name_ of a country can't be reliably retrieved. (Other more complex properties, I can understand).

PS: European Union (ee) is another file which uses a different convention.

**Comment by geraldb** [comment]
@mn113 Welcome. Good points. If you're interested in a discussion, please post your great comments, questions and suggestions to the [mailing list/forum](https://groups.google.com/group/openmundi). The issues here are only for tracking bugs. Thanks. Cheers.
