### ISSUE TITLE
South Sudan capital lat/long

### ISSUE THREAD

**Issue by mn113** [factbook/factbook.json#5]
In `od.json` the coordinate string is missing a comma.

`
    "Capital": {
      "name": {
        "text": "Juba"
      },
      "geographic coordinates": {
        "text": "04 51 N 31 37 E"
      },
`
Should be `"04 51 N, 31 37 E"` to avoid problems down the line.
It's the only example of this kind I found in my use of the repo so far.

**Comment by geraldb** [comment]
@mn113 Thanks for your effort in double checking. If you're interested in discussions please send your comments (and questions) to the [mailing list / forum](https://groups.google.com/group/openmundi). Thanks. Keep it up.  Added your comments to the new [NOTES.md](https://github.com/opendatajson/factbook.json/blob/master/NOTES.md) page. Cheers. See the source/orginal -> https://www.cia.gov/library/publications/the-world-factbook/geos/od.html
