### ISSUE TITLE
Wrong field in Vanuatu record?

### ISSUE THREAD

**Issue by nvitucci** [factbook/factbook.json#6]
There is a field starting with a dot, `.highest court(s)` (nh.json#L418). Is it intended?

**Comment by geraldb** [comment]
@nvitucci Thanks for reporting. You have to ask the CIA ;-) It's just gets converter 1:1 as is without any clean-up. Cheers.

**Comment by geraldb** [comment]
Running an update today to re-generate - your reported error is now fixed - see <https://github.com/factbook/factbook.json/blob/master/australia-oceania/nh.json#L437>. Cheers. Prost.
