### ISSUE TITLE
convert to ISO

### ISSUE THREAD

**Issue by alexmac131** [factbook/factbook.json#7]
Why not just transform the country codes to ISO?  Not a bug, a feature request

**Comment by geraldb** [comment]
For questions and comments, please see <https://github.com/opendatajson/factbook.json#questions-comments>.

**Comment by geraldb** [comment]
Anyways, for others - the factbook has many more entities / countries than ISO and sometimes with a different definition - it's NOT an easy 1:1 mapping, see <https://www.cia.gov/library/publications/the-world-factbook/appendix/appendix-d.html>.
