### ISSUE TITLE
Stray HTML spans

### ISSUE THREAD

**Issue by richardtallent** [factbook/factbook.json#8]
Hi,

I love this little library! I run a database within our intranet that has some geography-tagged company information, and I've been able to integrate some of this dataset with it automatically, which provides some nice high-level detail before getting to our actual business-related information.

Today I noticed something that would be great if it can be fixed, but if not, NBD. Some of the JSON files contain unnecessary SPAN tags with gobs of inline CSS styling that doesn't really add to the content semantically, and could cause visual anomalies on sites expecting to set their own fonts and such. This seems to happen mostly with notes and with names of ambassadors. I noticed it accidentally when searching for CSS font-family rules across my site.

I would recommend stripping all style attributes from spans, and if that leaves them with no attributes, remove them entirely. (There are also some class tags, but those seem to be a mix of semantic and presentation, and they're less likely to conflict with the site using them.)

Files currently exhibiting this issue include: as, ba, bt, cn, cu, ee, es, fs, gg, gj, hk, ks, ma, md, mg, mv, pm, sp, um, and xx.

**Comment by geraldb** [comment]
Thanks for reporting. The CIA has changed the format starting with the new year (Jan/2021).  Now actually offering - what looks like unofficial / undocumented -  json datasets.

The plan is to wait  (and observe) another couple of weeks (and updates) - assuming that the (new undocumented json) format stabilizes (gets cleaned up by the CIA itself) - and - thank you! - yes, document new quirks (such as inline stray html spans) that look like good candidates to clean-up / improve when outputing / generating  the simpler converted json format.

**Comment by geraldb** [comment]
With the latest update the datasets get now santizized, that is, span & div tags get unwrapped, that is, replaced with the inner content / text only.    Please, double check if you can still find some span or div tags - they should be gone now.  Cheers.
