### ISSUE TITLE
Missing closing parenthesis on data value in cq.sjon

### ISSUE THREAD

**Issue by dcalano** [factbook/factbook.json#9]
Hi, in the cq.json file (Northern Mariana Islands) the language data value is missing a parenthesis for the ["People and Society"]["Languages"]["text"] attribute.

`"Languages": {
      "text": "Philippine languages 32.8%, Chamorro (official) 24.1%, English (official) 17%, other Pacific island languages 10.1% (includes Carolinian (official), Chinese 6.8%, other Asian languages 7.3%, other 1.9% (2010 est.)"
    },`

(includes Carolinian (official)
should be
(includes Carolinian (official))

Also in the mz.json the language string is missing a % symbol for the "Nyanja 8.1" list item

Thank you for the repo, it is extremely useful!

**Comment by geraldb** [comment]
Thanks for reporting.
Sorry not trying to be funny - but not sure what I can do - please, report the data errors (upstream) at the Central Intelligence Agency (CIA) - see <https://www.cia.gov/the-world-factbook/> for the source that gets reformatted 1:1 with errors, quirks and all :-).

**Comment by dcalano** [comment]
Hi, sorry, did not realize the original data was erroneous :( Thank you
